### ISSUE TITLE
是否计划支持linux？

### ISSUE THREAD

**Issue by rainoffallingstar** [OpenJarvisAI/TianMu#3]
rt

**Comment by OpenJarvisAI** [comment]
你好，感谢关注，我们计划支持Linux。
目前已经推出Windows, macOS, Android，等到产品打磨的差不多了之后会发布Linux版本。
Tianmu本身采用跨平台语言开发，天然支持多平台。

star我们的进度或者加入社群，第一时间获取更新讯息

**Comment by rainoffallingstar** [comment]
感谢告知
